added helm chart to delete terminated/nodeshutdown pods in gke clusters.
Facets-cloud/helm-charts pull request #1
Opened 2023-01-31 10:06 UTC by ShrinidhiFCTS23

2023-02-01 06:47 UTC, rr0hit requested changes

2023-02-01 06:47 UTC, rr0hit commented on gke-pods-cleanup/README.md
> +## Values
The value where user can pass grep expression is not documented

2023-02-01 06:47 UTC, rr0hit commented on gke-pods-cleanup/templates/cronjob.yaml
> +    spec:
Add concurrencyPolicy forbid

2023-02-01 06:47 UTC, rr0hit commented on gke-pods-cleanup/templates/cronjob.yaml
> +              - "kubectl get pods --all-namespaces | grep -E '{{ .Values.pods }}' | awk '{print $2}' | xargs kubectl delete pod"
if pod is in different namespace this will fail. as kubectl delete command is running for default ns. You need to take namespace as input and work in that namespace. also instead of grep use something like https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/ . Make the variable name podStatusesToCleanUp

2023-02-01 06:47 UTC, rr0hit commented on gke-pods-cleanup/templates/cronjob.yaml
> +                  cpu: 100m
seems too much

2023-02-03 06:34 UTC, rr0hit requested changes

2023-02-03 06:34 UTC, rr0hit commented on gke-pods-cleanup/Chart.yaml
> +name: deletePods
Chart name need not be camel cased. delete-pods-by-status seems a better name.

2023-02-03 06:34 UTC, rr0hit commented on gke-pods-cleanup/templates/cronjob.yaml
> +              - "kubectl delete pods --field-selector=status.phase={{ .Values.podStatusesToCleanUp }} -n {{ .Values.namespace }}"
have you tested with multiple statuses? Does this work with comma separated statuses?

2023-02-03 16:41 UTC, ShrinidhiFCTS23 commented on gke-pods-cleanup/templates/cronjob.yaml
> +              - "kubectl delete pods --field-selector=status.phase={{ .Values.podStatusesToCleanUp }} -n {{ .Values.namespace }}"
This does not work with comma separated statuses as if we use command like kubectl delete pods --field-selector=status.phase= Failed,status.Succeeded it will look for pods with failed and succeeded status and it will say no resources found.
https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#chained-selectors
<img width="1005" alt="Screenshot 2023-02-03 at 9 19 18 PM" src="https://user-images.githubusercontent.com/117271152/216647966-3d895210-97c4-4d45-bbf1-aa01eaf59551.png">

Also this --field-selector status.phase=Failed will delete not just NodeShutdown and Terminated pods but also Completed pods
<img width="960" alt="Screenshot 2023-02-03 at 9 26 42 PM" src="https://user-images.githubusercontent.com/117271152/216649185-0ba8e93e-2072-495e-9daf-c53d3e862ad1.png">

To delete pods with multiple statuses we might need to use grep command 
<img width="965" alt="Screenshot 2023-02-03 at 10 05 28 PM" src="https://user-images.githubusercontent.com/117271152/216657441-650c791c-a678-4b56-bfb1-9edf9262b379.png">

2023-02-07 05:07 UTC, rr0hit requested changes

2023-02-07 05:07 UTC, rr0hit commented on gke-pods-cleanup/README.md
> +- "Pending"
Remove Pending and Running from here. Provide Terminated, NodeShutdown for now

2023-02-07 05:07 UTC, rr0hit commented
Also update the Readme with proper default values

2023-03-06 05:05 UTC, merged