Wetty azure
Facets-cloud/helm-charts pull request #3
Opened 2023-04-22 13:32 UTC by aditya-facets

Added helm chart for azure logging substack 

# Testing 
- When additional mounting is disabled 
``` 
wettysshAdditionalVolumes:
  enabled: false
```
PVC
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/111746197/233787554-bbbd9d44-62a3-48fa-99bb-a54485f06d36.png">
Pods status 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/111746197/233787574-08d89ca3-97bb-4a62-a0cc-9d34530b74ec.png">

- When additional mounting is enabled 
``` 
wettysshAdditionalVolumes:
  enabled: true
```
-  event from wetty-ssh pod when logs-pvc is not available to be additionally mounted
     
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/111746197/233787732-28bb9589-515a-483d-a498-78e838d2376e.png">

> When logs pvc was added additionaly to be mounted 

   
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/111746197/233787777-919a9cc8-c401-4f6f-9977-9cf9347eb74f.png">
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/111746197/233787794-a9e03c92-4563-44bc-bcdf-bc7d073a19f0.png">
       

> Pod status 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/111746197/233787868-4278b834-4d52-405c-aa73-6223d99299ce.png">
      

> Services for wetty and wetty-ssh 

<img width="880" alt="image" src="https://user-images.githubusercontent.com/111746197/233787903-a94ea4a2-1bf4-426d-91bd-bfb2a30131a1.png">

2023-04-24 08:25 UTC, rr0hit requested changes

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +apiVersion: v1
skip this secret and all references to it

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +      - hostPath:
Remove this and corresponding mount

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +      - name: logs-vol-alpha
Rename to logs-vol-azure-files

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/templates/storage.yaml
> +      storage: {{ .Values.persistentVolumeClaims.storageSize }}
check if you increase this value is the volume autoexpanding or not

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/values.yaml
> +chartName: loggingstack
Organize the values properly. Users should be able to understand the structure. 

gloabal: (if any)
wetty:
wetty-ssh:
fluentd:
logs-volume:

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/values.yaml
> +priorityClass:
Take this as 

fluentd: 
  priorityClassName: <>

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +              memory: 4Gi
Take these values as paramenters. Keep defaults low. 0.5core and 1GB

2023-04-24 08:25 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +          - mountPath: /var/log/alpha/efs
let the logs path be /var/log/efs. If they mount existing pvc let them provide a different mount path

2023-04-24 11:58 UTC, aditya-facets commented on azure-logging-stack/templates/storage.yaml
> +      storage: {{ .Values.persistentVolumeClaims.storageSize }}
# Testing 

**Volume expansion** 

- `storageSize: 15Gi`

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/111746197/233986910-0385d50c-02b0-492b-9127-7fe08dc394a5.png">

- `storageSize: 20Gi`

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/111746197/233989395-af921780-bb84-4a65-8dba-8f3244b82430.png">

2023-04-24 12:55 UTC, rr0hit commented on azure-logging-stack/templates/fluentd.yaml
> +        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
remove this annotation

2023-04-24 12:55 UTC, rr0hit commented on azure-logging-stack/templates/storage.yaml
delete the file

2023-04-24 12:55 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
remove this annotation

2023-04-24 12:55 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +        sidecar.istio.io/inject: "true"
remove these annotations

2023-04-24 12:55 UTC, rr0hit commented on azure-logging-stack/values.yaml
> +  chartName: loggingstack
why take this? Just use Release.Name that is available by default

2023-04-24 13:11 UTC, rr0hit commented on azure-logging-stack/templates/fluentd.yaml
> +  storageClassName: {{ .Values.logsVolume.storageClassName }}
keep this fixed to the azure files one

2023-04-24 13:11 UTC, rr0hit commented on azure-logging-stack/templates/fluentd.yaml
> +    - {{ .Values.logsVolume.persistentVolumeClaims.accessMode }}
always readwritemany as fluentd pods will use this

2023-04-24 13:11 UTC, rr0hit commented on azure-logging-stack/values.yaml
> +  persistentVolumeClaims:
make persistentVolumeClaims -> persistentVolumeClaim

2023-04-24 13:11 UTC, rr0hit commented on azure-logging-stack/templates/fluentd.yaml
> +        - name: logs-vol
lets have the name here also set to logs-vol-azure-files

2023-04-25 05:58 UTC, rr0hit requested changes

2023-04-25 05:58 UTC, rr0hit commented on azure-logging-stack/Chart.yaml
> +name: azure-logging-stack
azure-nfs-log-collector

2023-04-25 05:58 UTC, rr0hit commented on azure-logging-stack/templates/fluentd.yaml
> +  namespace: default
dont hardcode namepace

2023-04-25 05:58 UTC, rr0hit commented on azure-logging-stack/values.yaml
> +  wettysshAdditionalVolumes:
just have
wettysshAdditionalVolumes:
      - name: logs-vol
        mountPath: /var/log/efs
        claimName: logs-pvc
     - name: my2nd
       mountPath: /var/log/efs
       claimName: logs-pvc2

2023-04-25 05:58 UTC, rr0hit commented on azure-logging-stack/templates/wetty-ssh.yaml
> +            storage: 5Gi
make this configurable

2023-04-26 16:16 UTC, rr0hit requested changes

2023-04-26 16:16 UTC, rr0hit commented on azure-nfs-log-collector/templates/fluentd.yaml
> +  storageClassName: ccazfile
Let's take this as a helm param afterall.

2023-04-27 05:00 UTC, rr0hit requested changes

2023-04-28 12:11 UTC, merged